language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.node_modules
  - $HOME/.chromium_dist
branches:
  only:
    - master
    - travis
    - /^release-.+$/
    - /^dev-.+/

before_install:
  - nvm install 7
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - OLD_VERSION=`mvn help:evaluate -Dexpression=project.version 2>/dev/null | grep -Ev "(^\[|Download\w+:)"`
  - NEW_VERSION=${OLD_VERSION%-SNAPSHOT}-dev-`printf %d $TRAVIS_BUILD_NUMBER`
  - echo "Building version $NEW_VERSION"
  - mvn versions:set -DnewVersion=$NEW_VERSION

install:
  - mvn install -Dteavm.build.all=false -P with-idea -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - pushd tests/src/test/js
  - npm config set prefix=$HOME/.node_modules
  - npm install
  - npm run build
  - popd

script:
  - mvn -e test -P \!htmlUnit
  - BASE_PATH=`pwd`
  - pushd tests/src/test/js
  - firefox index.html &
  - FIREFOX_PID=$!
  - node start.js $BASE_PATH/tests/target/js-tests
  - node start.js $BASE_PATH/html4j/target/js-tests
  - kill $FIREFOX_PID
  - popd

after_success: >
   if [[ "${TRAVIS_PULL_REQUEST:-unknown}" == "false" && $TRAVIS_BRANCH == dev-* ]] ; then
     export NEW_VERSION
     export TEAVM_FTP_HOST
     export TEAVM_FTP_LOGIN
     export TEAVM_FTP_PASSWORD
     mvn deploy -Dteavm.build.all=false -DskipTests --settings travis-settings.xml -P deploy-to-bintray -P with-idea && \
     ./update-idea-repository.sh
   fi
after_script:
  - rm -rf $HOME/.m2/repository/org/teavm