name: Build
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform:
        - c
        - js
        - wasm
        - wasi
        - wasm-gc
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - uses: gradle/gradle-build-action@v2
    - if: ${{ matrix.platform == 'wasi' }}
      uses: bytecodealliance/actions/wasmtime/setup@v1
    - if: ${{ matrix.platform == 'wasi' }}
      run: |
        mkdir -p "$HOME/.wasmtime/bin/"
        echo 'wasmtime "$@"'> "$HOME/.wasmtime/bin/wasmtime"
        chmod +x "$HOME/.wasmtime/bin/wasmtime"
    - run: |
        platforms=("c" "js" "wasm" "wasi" "wasm-gc")
        args=()
        for v in "${platforms[@]}"
        do
          if [[ "${{ matrix.platform }}" != "$v" ]]; then
            args+=("-Pteavm.tests.${v}=false")
          fi
        done
        echo "${args[@]}"
        ./gradlew "${args[@]}" test
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: "test-reports-${{ matrix.platform }}"
        path: "tests/build/reports/tests/test"
  checkstyle:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - uses: gradle/gradle-build-action@v2
      - run: |
          ./gradlew build -x test